name: com.nixplugin
main: com.nixplugin.Plugin
version: 1.0.0
description: Plugin du serveur Nix
author: Florent
permissions:
 nixplugin.eclair:
  description: Pour envoyer un eclair.
  default: op
 gamemode.survival:
  description: Pour se mettre en gamemode 0.
  default: op
 gamemode.creative:
  description: Pour se mettre en gamemode 1.
  default: op
 gamemode.adventure:
  description: Pour se mettre en gamemode 2.
  default: op
 gamemode.spectator:
  description: Pour se mettre en gamemode 3.
  default: op
 warps.use:
  description: Pour utiliser les warps.
  default: op
 warps.manage:
  description: Pour manager les warps.
  default: op
commands:
 roll:
  description: Pour lancer un de.
 tell:
  description: Pour envoyer un message prive.
 compass:
  description: Pour faire pointer sa boussole.
 warp:
  description: Pour utiliser ou manager les warps.
 mana:
  description: Pour voir ou changer le niveau vanilla d'un joueur.
 gm:
  description: Pour changer de gamemode.
 eclair:
  description: Pour envoyer un eclair.